### ISSUE TITLE
postgresql15

### ISSUE THREAD

**Issue by WLlaura** [comagic/pg_export#27]
Привет, тестирую 15 постгрес, напоролся на вот такое с pg_export

\Users\user\AppData\Local\Programs\Python\pg_export-master\pg_export\templates\pg_14.x
\Users\user\AppData\Local\Programs\Python\pg_export-master\pg_export\templates\pg_15.x
Создал всё заработало, но не знаю насколько правильное решение, под 15 наверное свои исходники должны быть

**Comment by WLlaura** [comment]
Некорректно работает, ловлю расхождения((
 
![photo_2022-12-29_02-15-06](https://user-images.githubusercontent.com/109145534/209890250-4d9ab1f3-fc91-4e3b-a198-515640e0ffea.jpg)

**Comment by andruche** [comment]
А что не так с правами? По описанию не понял, слева есть права справа нет, всё сходится)
